version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "github-actions"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "go"
    groups:
      golang-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "javascript"
    groups:
      radix:
        patterns:
          - "@radix-ui/*"
      react:
        patterns:
          - "react*"
          - "@types/react*"
      dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "@radix-ui/*"
          - "react*"
          - "@types/react*"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"] 